---
:concurrency: 5
:timeout: 25
:verbose: false
:queues:
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

# Production settings
production:
  :concurrency: 10

# Development settings
development:
  :concurrency: 2

# Test settings
test:
  :concurrency: 1

